apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: my-log-event-sink
spec:
  source:
    ref:
      kind: InMemoryChannel
      apiVersion: messaging.knative.dev/v1
      name: messages
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: my-log-sink