apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: my-timer-event-source
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: my-timer-source
    properties:
      message: "Hello world!"
  sink:
    ref:
      kind: InMemoryChannel
      apiVersion: messaging.knative.dev/v1
      name: messages